# Generated by Django 4.2.26 on 2026-02-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='client_comment',
            field=models.TextField(blank=True),
        ),
    ]
